# source "git@gitlab.alibaba-inc.com:alipods/specs.git"
# source "git@gitlab.alibaba-inc.com:alipods/specs-mirror.git"
platform :ios


target 'SwiftExample' do
	
  platform:ios, '15.0'
  use_frameworks!
  
	#pod 'wax', :git=>'https://github.com/alibaba/wax.git', :tag=>'1.1.0'
    #pod 'wax', :git=>'git@github.com:alibaba/wax.git', :commit=>'5c762ad'
    
    pod 'lua_ios', :path => '/Users/andy/Projects/lua_xcframework_pod/lua_ios.podspec'
    
    pod 'wax', :path=>'../../'
end
